name: wekan
version: 1.0.3
apiVersion: v1
description: Open Source kanban
home: https://wekan.github.io/
icon: https://wekan.github.io/wekan-logo.svg
sources:
  - https://github.com/wekan/wekan
maintainers:
  - name: technotaff
    email: github@randall.cc
  - name: jiangytcn
    email: jiangyt.cn@gmail.com
engine: gotpl
